### ISSUE TITLE
Doesnt make application

### ISSUE THREAD

**Issue by tomihad-ul-aibak** [Nuggies-bot/applications-example#1]

**Comment by proniotov** [comment]
Code? Any errs?

**Comment by tomihad-ul-aibak** [comment]
Wait

**Comment by tomihad-ul-aibak** [comment]
it doesnt show error

**Comment by tomihad-ul-aibak** [comment]
it sometimes show something 'channelID' null

**Comment by tomihad-ul-aibak** [comment]
and cant make 1 without emoji

**Comment by Assassin-1234** [comment]
please open an issue over at https://github.com/Nuggies-bot/nuggies-npm/issues/new/choose ** and use the issue template
